import type { MemoryAsset } from "./types";

export const memoryCandidates: MemoryAsset[] = [
  {
    id: "mem-candidate-1",
    appId: "general",
    type: "preference",
    title: "输出使用简体中文，结构清晰但不过度展开",
    content:
      "用户偏好专业、简洁的简体中文输出。需要结构化，但不要把简单问题写成冗长报告。",
    status: "candidate",
    confidence: 0.94,
    scope: "user",
    tags: ["沟通偏好", "输出风格"],
    sourceConversationTitle: "Forge Memory 产品设计",
    evidence: [
      {
        id: "ev-1",
        label: "用户明确指令",
        quote: "Most Important:Always respond in Chinese-simplified",
        source: "AGENTS.md",
        time: "今天 15:08",
      },
    ],
    createdAt: "今天 15:08",
    updatedAt: "今天 15:08",
  },
  {
    id: "mem-candidate-2",
    appId: "general",
    type: "decision",
    title: "知识库产品不做传统 RAG，优先做工作记忆",
    content:
      "Forge Agent 的知识模块应从聊天协作中沉淀偏好、技能、规则和流程，而不是以文件上传和向量检索为核心。",
    status: "candidate",
    confidence: 0.89,
    scope: "app",
    tags: ["产品决策", "Forge Memory"],
    sourceConversationTitle: "知识库模块方向讨论",
    evidence: [
      {
        id: "ev-2",
        label: "用户判断",
        quote: "应该是把聊天记录里的知识抽出来，这是最有价值的，而且有特色的",
        source: "聊天记录",
        time: "今天 15:37",
      },
    ],
    createdAt: "今天 15:37",
    updatedAt: "今天 15:37",
  },
  {
    id: "mem-candidate-3",
    appId: "general",
    type: "skill",
    title: "知识产品设计评估方法",
    content:
      "评估知识库产品时，先从用户真实工作目标出发，再区分事实知识、记忆知识、技能知识和流程规范。",
    status: "candidate",
    confidence: 0.86,
    scope: "team",
    tags: ["产品设计", "方法论"],
    sourceConversationTitle: "知识库模块方向讨论",
    evidence: [
      {
        id: "ev-3",
        label: "对话共识",
        quote: "有的聊天不只是文本+图片，还有业务流程/工作规范",
        source: "聊天记录",
        time: "今天 15:42",
      },
    ],
    createdAt: "今天 15:42",
    updatedAt: "今天 15:42",
    triggers: ["设计知识库", "评估 RAG", "沉淀工作方式", "做产品方案"],
    inputs: ["目标用户", "协作场景", "已有资料", "现有工作流"],
    steps: [
      "从用户为什么需要这个能力开始",
      "识别聊天中可沉淀的偏好、决策、技能和规则",
      "判断哪些资产会改变 Agent 行为",
      "只把高价值资产做成可确认、可追溯的工作记忆",
    ],
    outputFormat: "产品定位、核心交互、MVP 范围、后续演进",
    guardrails: ["不要暴露 embedding / chunk 等技术细节", "技能和规则必须人工确认"],
  },
  {
    id: "mem-candidate-4",
    appId: "general",
    type: "rule",
    title: "Forge UI 页面开发必须优先使用 Kit 组件",
    content:
      "新增或修改业务页面时，优先从 @forge-ui-official/core 导入组件，颜色使用 fg-* token，图标使用 solar-icon-set。",
    status: "candidate",
    confidence: 0.96,
    scope: "app",
    tags: ["工程规范", "UI 规范"],
    sourceConversationTitle: "项目 AGENTS.md",
    evidence: [
      {
        id: "ev-4",
        label: "项目铁律",
        quote: "组件只从 @forge-ui-official/core 导入。颜色只用 fg-* token。Icon 用 solar-icon-set。",
        source: "AGENTS.md",
        time: "今天 14:50",
      },
    ],
    createdAt: "今天 14:50",
    updatedAt: "今天 14:50",
    appliesTo: ["新增页面", "修改前端 UI", "制作交互原型"],
    requiredChecks: [
      "先看对应 cases 示例",
      "使用 AppLayout 承载业务页面",
      "图标颜色通过 color prop 设置",
    ],
    blockedActions: ["手搓 Kit 已有组件", "使用 Tailwind 默认色", "自行修改 base URL 路由"],
    severity: "block",
  },
];

export const activeMemories: MemoryAsset[] = [
  {
    id: "mem-active-1",
    appId: "general",
    type: "preference",
    title: "先给结论，再给必要细节",
    content: "用户更喜欢先看到明确判断，然后再看权衡、风险和下一步。",
    status: "active",
    confidence: 0.91,
    scope: "user",
    tags: ["沟通偏好"],
    sourceConversationTitle: "多轮产品讨论",
    evidence: [
      {
        id: "ev-a1",
        label: "多次反馈",
        quote: "有道理，继续；不错，有点样子了。",
        source: "聊天记录",
        time: "昨天",
      },
    ],
    createdAt: "昨天",
    updatedAt: "今天",
  },
  {
    id: "mem-active-2",
    appId: "general",
    type: "skill",
    title: "PR 风险评审",
    content: "审 PR 时按严重度排序，必须给文件位置、风险解释和最小修复建议。",
    status: "active",
    confidence: 0.88,
    scope: "team",
    tags: ["研发", "评审"],
    sourceConversationTitle: "代码评审样例",
    evidence: [
      {
        id: "ev-a2",
        label: "输出样例",
        quote: "按「问题严重度」排序而不是按文件。",
        source: "聊天记录",
        time: "昨天",
      },
    ],
    createdAt: "昨天",
    updatedAt: "今天",
    triggers: ["审 PR", "看 diff", "安全和性能"],
    inputs: ["PR 链接", "diff", "测试报告"],
    steps: ["读变更范围", "识别安全/性能/测试风险", "按严重度排序", "给最小修复建议"],
    outputFormat: "严重问题 / 中等风险 / 建议优化 / 测试缺口",
    guardrails: ["不要泛泛而谈", "必须引用具体文件或证据"],
  },
  {
    id: "mem-active-3",
    appId: "general",
    type: "rule",
    title: "高影响知识必须确认后生效",
    content: "会改变 Agent 行为的技能、规则、流程必须经用户确认后进入 active 状态。",
    status: "active",
    confidence: 0.93,
    scope: "app",
    tags: ["信任", "产品规则"],
    sourceConversationTitle: "Forge Memory PRD",
    evidence: [
      {
        id: "ev-a3",
        label: "产品原则",
        quote: "技能和流程必须人工确认。",
        source: "聊天记录",
        time: "今天",
      },
    ],
    createdAt: "今天",
    updatedAt: "今天",
    appliesTo: ["记忆抽取", "技能保存", "规则保存"],
    requiredChecks: ["展示来源证据", "展示影响范围", "允许修改或忽略"],
    blockedActions: ["自动启用阻断规则", "无证据保存团队流程"],
    severity: "warn",
  },
];
